// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: offerings.proto

package twirp_sm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AppCode     string  `protobuf:"bytes,2,opt,name=app_code,json=appCode,proto3" json:"app_code,omitempty"`
	BarCode     string  `protobuf:"bytes,3,opt,name=bar_code,json=barCode,proto3" json:"bar_code,omitempty"`
	BarCodeStd  string  `protobuf:"bytes,4,opt,name=bar_code_std,json=barCodeStd,proto3" json:"bar_code_std,omitempty"`
	Kind        string  `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	UnitCode    string  `protobuf:"bytes,6,opt,name=unit_code,json=unitCode,proto3" json:"unit_code,omitempty"`
	Price       float64 `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	OpenForSale string  `protobuf:"bytes,8,opt,name=open_for_sale,json=openForSale,proto3" json:"open_for_sale,omitempty"`
	Active      string  `protobuf:"bytes,9,opt,name=active,proto3" json:"active,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offerings_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_offerings_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_offerings_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetAppCode() string {
	if x != nil {
		return x.AppCode
	}
	return ""
}

func (x *Item) GetBarCode() string {
	if x != nil {
		return x.BarCode
	}
	return ""
}

func (x *Item) GetBarCodeStd() string {
	if x != nil {
		return x.BarCodeStd
	}
	return ""
}

func (x *Item) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Item) GetUnitCode() string {
	if x != nil {
		return x.UnitCode
	}
	return ""
}

func (x *Item) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetOpenForSale() string {
	if x != nil {
		return x.OpenForSale
	}
	return ""
}

func (x *Item) GetActive() string {
	if x != nil {
		return x.Active
	}
	return ""
}

type ItemList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ItemList) Reset() {
	*x = ItemList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offerings_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemList) ProtoMessage() {}

func (x *ItemList) ProtoReflect() protoreflect.Message {
	mi := &file_offerings_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemList.ProtoReflect.Descriptor instead.
func (*ItemList) Descriptor() ([]byte, []int) {
	return file_offerings_proto_rawDescGZIP(), []int{1}
}

func (x *ItemList) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ItemsQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IncludeInactive       *bool   `protobuf:"varint,1,opt,name=include_inactive,json=includeInactive,proto3,oneof" json:"include_inactive,omitempty"`
	Kind                  *string `protobuf:"bytes,2,opt,name=kind,proto3,oneof" json:"kind,omitempty"`
	IncludeNotOpenForSale *bool   `protobuf:"varint,3,opt,name=include_not_open_for_sale,json=includeNotOpenForSale,proto3,oneof" json:"include_not_open_for_sale,omitempty"`
}

func (x *ItemsQuery) Reset() {
	*x = ItemsQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offerings_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemsQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemsQuery) ProtoMessage() {}

func (x *ItemsQuery) ProtoReflect() protoreflect.Message {
	mi := &file_offerings_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemsQuery.ProtoReflect.Descriptor instead.
func (*ItemsQuery) Descriptor() ([]byte, []int) {
	return file_offerings_proto_rawDescGZIP(), []int{2}
}

func (x *ItemsQuery) GetIncludeInactive() bool {
	if x != nil && x.IncludeInactive != nil {
		return *x.IncludeInactive
	}
	return false
}

func (x *ItemsQuery) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *ItemsQuery) GetIncludeNotOpenForSale() bool {
	if x != nil && x.IncludeNotOpenForSale != nil {
		return *x.IncludeNotOpenForSale
	}
	return false
}

var File_offerings_proto protoreflect.FileDescriptor

var file_offerings_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xf5, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x61, 0x72,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x62, 0x61, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x5f, 0x73, 0x74, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x61, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x53, 0x74, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x6e,
	0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x6e, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x22, 0x0a,
	0x0d, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x73, 0x61, 0x6c, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x70, 0x65, 0x6e, 0x46, 0x6f, 0x72, 0x53, 0x61, 0x6c,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x27, 0x0a, 0x08, 0x49, 0x74, 0x65,
	0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x22, 0xd0, 0x01, 0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x12, 0x2e, 0x0a, 0x10, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x69, 0x6e, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0f, 0x69,
	0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x49, 0x6e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x88, 0x01,
	0x01, 0x12, 0x17, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x01, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x88, 0x01, 0x01, 0x12, 0x3d, 0x0a, 0x19, 0x69, 0x6e,
	0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x66,
	0x6f, 0x72, 0x5f, 0x73, 0x61, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x02, 0x52,
	0x15, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x4e, 0x6f, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x46,
	0x6f, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x69, 0x6e,
	0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x69, 0x6e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x42, 0x07,
	0x0a, 0x05, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x42, 0x1c, 0x0a, 0x1a, 0x5f, 0x69, 0x6e, 0x63, 0x6c,
	0x75, 0x64, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x66, 0x6f, 0x72,
	0x5f, 0x73, 0x61, 0x6c, 0x65, 0x32, 0x3d, 0x0a, 0x11, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x0e, 0x43, 0x61,
	0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x0b, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x09, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x0a, 0x5a, 0x08, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2e, 0x73, 0x6d,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_offerings_proto_rawDescOnce sync.Once
	file_offerings_proto_rawDescData = file_offerings_proto_rawDesc
)

func file_offerings_proto_rawDescGZIP() []byte {
	file_offerings_proto_rawDescOnce.Do(func() {
		file_offerings_proto_rawDescData = protoimpl.X.CompressGZIP(file_offerings_proto_rawDescData)
	})
	return file_offerings_proto_rawDescData
}

var file_offerings_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_offerings_proto_goTypes = []interface{}{
	(*Item)(nil),       // 0: Item
	(*ItemList)(nil),   // 1: ItemList
	(*ItemsQuery)(nil), // 2: ItemsQuery
}
var file_offerings_proto_depIdxs = []int32{
	0, // 0: ItemList.items:type_name -> Item
	2, // 1: ItemsQueryService.CallItemsQuery:input_type -> ItemsQuery
	1, // 2: ItemsQueryService.CallItemsQuery:output_type -> ItemList
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_offerings_proto_init() }
func file_offerings_proto_init() {
	if File_offerings_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_offerings_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_offerings_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_offerings_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemsQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_offerings_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_offerings_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_offerings_proto_goTypes,
		DependencyIndexes: file_offerings_proto_depIdxs,
		MessageInfos:      file_offerings_proto_msgTypes,
	}.Build()
	File_offerings_proto = out.File
	file_offerings_proto_rawDesc = nil
	file_offerings_proto_goTypes = nil
	file_offerings_proto_depIdxs = nil
}
